name: tilchoy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  form_builder: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
